import * as os from 'node:os';
import * as path from 'node:path';

export interface StatusLineSetting {
  type: string;
  command: string;
  padding?: number;
  refreshInterval?: number;
  hideVimModeIndicator?: boolean;
}

export interface PatchResult {
  json: string;
  /** The setting we displaced, so uninstall can put it back. */
  replaced?: StatusLineSetting;
}

/** Honours CLAUDE_CONFIG_DIR, which relocates the whole `~/.claude` tree. */
export function claudeConfigDir(env: NodeJS.ProcessEnv = process.env): string {
  const override = env.CLAUDE_CONFIG_DIR?.trim();
  return override ? override : path.join(os.homedir(), '.claude');
}

export function claudeSettingsPath(env?: NodeJS.ProcessEnv): string {
  return path.join(claudeConfigDir(env), 'settings.json');
}

/** Quote a value for POSIX sh, including paths that contain quotes. */
export function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * The bridge script. Claude Code pipes its status line payload to this on
 * stdin and renders whatever it prints, so the script has two jobs: persist the
 * payload atomically for the extension, then produce a line for the terminal.
 *
 * Deliberately POSIX sh with no node dependency — it runs on whatever shell the
 * user's Claude Code session happens to have.
 */
export function renderBridgeScript(stateDir: string, delegateCommand = ''): string {
  return `#!/bin/sh
# Generated by wx-vsce-claude-usage-ultra. Do not edit — reinstall from VS Code instead.
#
# Claude Code pipes its status line JSON to this script on stdin. We tee it to a
# file the extension watches, then render the line (delegating to a previously
# configured status line command when there was one).
set -u

STATE_DIR=${shQuote(stateDir)}
OUT="$STATE_DIR/current.json"
TMP="$OUT.$$"

mkdir -p "$STATE_DIR" 2>/dev/null || true
if cat > "$TMP" 2>/dev/null; then
  # Rename within the directory so the extension never reads a partial file.
  mv -f "$TMP" "$OUT" 2>/dev/null || rm -f "$TMP"
else
  rm -f "$TMP"
  exit 0
fi

DELEGATE=${shQuote(delegateCommand)}
if [ -n "$DELEGATE" ]; then
  exec sh -c "$DELEGATE" < "$OUT"
fi

# Fallback line. Field extraction is intentionally crude: it only affects what
# the terminal shows, never what the extension reads.
model=$(sed -n 's/.*"display_name":"\\([^"]*\\)".*/\\1/p' "$OUT" | head -n 1)
five=$(sed -n 's/.*"five_hour":{"used_percentage":\\([0-9.]*\\).*/\\1/p' "$OUT" | head -n 1)
week=$(sed -n 's/.*"seven_day":{"used_percentage":\\([0-9.]*\\).*/\\1/p' "$OUT" | head -n 1)

line=""
[ -n "$model" ] && line="$model"
[ -n "$five" ] && line="$line | 5h $(printf '%.0f' "$five" 2>/dev/null)%"
[ -n "$week" ] && line="$line | 7d $(printf '%.0f' "$week" 2>/dev/null)%"
printf '%s' "\${line# | }"
`;
}

function isStatusLineSetting(value: unknown): value is StatusLineSetting {
  return (
    typeof value === 'object' &&
    value !== null &&
    !Array.isArray(value) &&
    typeof (value as StatusLineSetting).command === 'string'
  );
}

function parseSettings(source: string | undefined): Record<string, unknown> {
  if (!source || !source.trim()) return {};
  const parsed: unknown = JSON.parse(source);
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error('Claude Code settings.json is not a JSON object.');
  }
  return parsed as Record<string, unknown>;
}

/** Read the `statusLine` command already configured, if any. */
export function existingStatusLine(source: string | undefined): StatusLineSetting | undefined {
  const settings = parseSettings(source);
  return isStatusLineSetting(settings.statusLine) ? settings.statusLine : undefined;
}

/** Point `statusLine` at our script, preserving every other setting. */
export function patchSettings(
  source: string | undefined,
  scriptPath: string,
  refreshInterval: number,
): PatchResult {
  const settings = parseSettings(source);
  const previous = isStatusLineSetting(settings.statusLine) ? settings.statusLine : undefined;

  settings.statusLine = {
    type: 'command',
    command: scriptPath,
    refreshInterval,
  } satisfies StatusLineSetting;

  return {
    json: `${JSON.stringify(settings, null, 2)}\n`,
    replaced: previous?.command === scriptPath ? undefined : previous,
  };
}

/** Undo {@link patchSettings}, restoring whatever we displaced. */
export function unpatchSettings(
  source: string,
  scriptPath: string,
  restore?: StatusLineSetting,
): { json: string; changed: boolean } {
  const settings = parseSettings(source);
  const current = settings.statusLine;

  if (!isStatusLineSetting(current) || current.command !== scriptPath) {
    return { json: source, changed: false };
  }
  if (restore) {
    settings.statusLine = restore;
  } else {
    delete settings.statusLine;
  }
  return { json: `${JSON.stringify(settings, null, 2)}\n`, changed: true };
}

/** What to show the user when we cannot safely edit settings.json ourselves. */
export function manualSnippet(scriptPath: string, refreshInterval: number): string {
  return JSON.stringify({ statusLine: { type: 'command', command: scriptPath, refreshInterval } }, null, 2);
}
