//! Writing `glsl-spec/src/generated/*.rs`.
//!
//! Determinism is the whole contract: two runs over the same checkout must
//! produce identical bytes, so nothing here reads a clock, iterates a hash map,
//! or depends on directory order. Every table is built from an already-sorted
//! `Vec` and the documentation pool is filled in that same order.

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::collect::{Function, Spec, Variable};

/// One generated file: a path relative to `generated/`, and its contents.
pub struct File {
    pub name: &'static str,
    pub contents: String,
}

/// The documentation pool: every distinct string once, with the slice each
/// entry points at.
struct Pool {
    chunks: Vec<String>,
    offsets: HashMap<String, (u32, u32)>,
    length: u32,
}

impl Pool {
    fn new() -> Pool {
        Pool { chunks: Vec::new(), offsets: HashMap::new(), length: 0 }
    }

    /// The slice for a string, adding it to the pool if it is new. Identical
    /// prose — and `sl4/` and `el3/` share a great deal of it — is stored once.
    fn intern(&mut self, text: &str) -> (u32, u32) {
        if text.is_empty() {
            return (0, 0);
        }
        if let Some(&slice) = self.offsets.get(text) {
            return slice;
        }
        let length = text.len() as u32;
        let slice = (self.length, length);
        self.offsets.insert(text.to_string(), slice);
        self.chunks.push(text.to_string());
        self.length += length;
        slice
    }
}

/// Render every generated file.
pub fn emit(spec: &Spec, commit: &str) -> Vec<File> {
    let mut pool = Pool::new();
    // Order matters: the two table files fill the pool that `docs.rs` renders.
    let functions = functions(spec, commit, &mut pool);
    let variables = variables(spec, commit, &mut pool);
    vec![
        File { name: "mod.rs", contents: module(spec, commit) },
        File { name: "families.rs", contents: families(spec, commit) },
        File { name: "functions.rs", contents: functions },
        File { name: "variables.rs", contents: variables },
        File { name: "docs.rs", contents: docs(&pool, commit) },
    ]
}

/// The header every generated file opens with — provenance and attribution,
/// per decision 0005.
fn header(commit: &str) -> String {
    format!(
        "\
// Generated by glsl-spec-gen. Do not edit by hand — edit the generator and run
// `cargo run -p glsl-spec-gen`, then commit the result.
//
// Source: docs.gl (github.com/BSVino/docs.gl) at commit
// {commit},
// directories sl4/ (desktop GLSL) and el3/ (GLSL ES).
//
// The prose in these tables is Khronos Group reference-page material,
// Copyright (c) 2011-2014 Khronos Group, distributed under the terms of the
// Open Publication License v1.0 (https://opencontent.org/openpub/). The docs.gl
// scaffolding that reshaped it into these pages is public domain. See
// docs/rfc/012-glsl-analyzer/decisions/0005-refpage-attribution.md and
// extensions/wgsl-shader/THIRD-PARTY-NOTICES.md.
//
// Desktop 4.60 and GLSL ES 3.20 have no column in docs.gl's version tables; the
// bits for them are copied from 4.50 and ES 3.10 respectively, which removed
// nothing. docs/rfc/012-glsl-analyzer/research/docs-gl.md §5.
"
    )
}

fn module(spec: &Spec, commit: &str) -> String {
    let mut out = header(commit);
    out.push_str(
        "\n\
//! The generated half of the spec. See the sibling modules for the tables and
//! `crate::model` for what the entries mean.

mod docs;
mod families;
mod functions;
mod variables;

pub use docs::DOCS;
pub use families::FAMILIES;
pub use functions::FUNCTIONS;
pub use variables::VARIABLES;

/// The tool that wrote these tables.
pub const GENERATOR: &str = \"glsl-spec-gen\";

",
    );
    let _ = writeln!(
        out,
        "/// The docs.gl commit the reference pages were read from.\n\
         pub const DOCS_GL_COMMIT: &str = \"{commit}\";"
    );
    let _ = writeln!(
        out,
        "\n/// How many builtin functions, variables and generic families the tables hold.\n\
         /// A cheap sanity check for anyone reviewing a regeneration diff.\n\
         pub const COUNTS: (usize, usize, usize) = ({}, {}, {});",
        spec.functions.len(),
        spec.variables.len(),
        spec.families.len()
    );
    out
}

fn families(spec: &Spec, commit: &str) -> String {
    let mut out = header(commit);
    out.push_str("\nuse crate::model::Family;\n\n");
    out.push_str("/// The generic families the reference pages use, sorted by name.\n");
    out.push_str("pub static FAMILIES: &[Family] = &[\n");
    for (name, members) in &spec.families {
        let members: Vec<String> = members.iter().map(|m| string(m)).collect();
        let _ = writeln!(
            out,
            "    Family {{ name: {}, members: &[{}] }},",
            string(name),
            members.join(", ")
        );
    }
    out.push_str("];\n");
    out
}

fn functions(spec: &Spec, commit: &str, pool: &mut Pool) -> String {
    let mut out = String::with_capacity(512 * 1024);
    out.push_str(&header(commit));
    out.push('\n');
    out.push_str(
        "use crate::model::{\n\
         \x20   BuiltinFunction, DocRef, FamilyId, Flow, Overload, Param, ParamDoc, TypeRef,\n\
         };\n\
         use crate::version::{DesktopMask, EsMask};\n\n\
         /// Every builtin function docs.gl documents, sorted by name.\n\
         pub static FUNCTIONS: &[BuiltinFunction] = &[\n",
    );
    for function in &spec.functions {
        emit_function(&mut out, function, spec, pool);
    }
    out.push_str("];\n");
    out
}

fn emit_function(out: &mut String, function: &Function, spec: &Spec, pool: &mut Pool) {
    let (doc_offset, doc_len) = pool.intern(&function.doc);
    let _ = writeln!(out, "    BuiltinFunction {{");
    let _ = writeln!(out, "        name: {},", string(&function.name));
    out.push_str("        overloads: &[\n");
    for overload in &function.overloads {
        let params: Vec<String> = overload
            .raw
            .params
            .iter()
            .map(|p| {
                format!(
                    "Param {{ name: {}, ty: {}, flow: Flow::{}, optional: {} }}",
                    string(&p.name),
                    type_ref(&p.ty, spec),
                    p.flow.variant(),
                    p.optional
                )
            })
            .collect();
        let _ = writeln!(
            out,
            "            Overload {{ ret: {}, params: &[{}], \
             desktop: DesktopMask::from_bits({:#06x}), es: EsMask::from_bits({:#04x}) }},",
            type_ref(&overload.raw.ret, spec),
            params.join(", "),
            overload.desktop,
            overload.es
        );
    }
    out.push_str("        ],\n");
    let _ = writeln!(out, "        doc: DocRef::new({doc_offset}, {doc_len}),");
    if function.param_docs.is_empty() {
        out.push_str("        param_docs: &[],\n");
    } else {
        out.push_str("        param_docs: &[\n");
        for (name, doc) in &function.param_docs {
            let (offset, len) = pool.intern(doc);
            let _ = writeln!(
                out,
                "            ParamDoc {{ name: {}, doc: DocRef::new({offset}, {len}) }},",
                string(name)
            );
        }
        out.push_str("        ],\n");
    }
    let _ = writeln!(
        out,
        "        desktop: DesktopMask::from_bits({:#06x}),\n\
         \x20       es: EsMask::from_bits({:#04x}),",
        function.desktop,
        function.es
    );
    out.push_str("    },\n");
}

fn variables(spec: &Spec, commit: &str, pool: &mut Pool) -> String {
    let mut out = String::with_capacity(64 * 1024);
    out.push_str(&header(commit));
    out.push('\n');
    out.push_str(
        "use crate::model::{BuiltinVariable, DocRef, Flow, StageMask};\n\
         use crate::version::{DesktopMask, EsMask};\n\n\
         /// Every predeclared `gl_*` variable docs.gl documents, sorted by name.\n\
         pub static VARIABLES: &[BuiltinVariable] = &[\n",
    );
    for variable in &spec.variables {
        emit_variable(&mut out, variable, pool);
    }
    out.push_str("];\n");
    out
}

fn emit_variable(out: &mut String, variable: &Variable, pool: &mut Pool) {
    let (offset, len) = pool.intern(&variable.doc);
    let _ = writeln!(out, "    BuiltinVariable {{");
    let _ = writeln!(out, "        name: {},", string(&variable.name));
    let _ = writeln!(out, "        ty: {},", string(&variable.ty));
    let _ = writeln!(out, "        stages: StageMask::from_bits({:#04x}),", variable.stages);
    let _ = writeln!(out, "        flow: Flow::{},", variable.flow.variant());
    let _ = writeln!(out, "        doc: DocRef::new({offset}, {len}),");
    let _ = writeln!(
        out,
        "        desktop: DesktopMask::from_bits({:#06x}),\n\
         \x20       es: EsMask::from_bits({:#04x}),",
        variable.desktop,
        variable.es
    );
    out.push_str("    },\n");
}

fn docs(pool: &Pool, commit: &str) -> String {
    let mut out = header(commit);
    let _ = write!(
        out,
        "\n/// Every description and parameter note in one string, sliced by\n\
         /// [`crate::model::DocRef`]. One pool rather than {} separate `&'static str`s:\n\
         /// it relocates once, compresses far better in wasm, and keeps the entries to\n\
         /// two `u32`s apiece.\n\
         pub static DOCS: &str = concat!(\n",
        pool.chunks.len()
    );
    for chunk in &pool.chunks {
        let _ = writeln!(out, "    {},", string(chunk));
    }
    out.push_str(");\n");
    out
}

/// A type as a `TypeRef` literal. Families are emitted as their index in the
/// generated `FAMILIES` table, which is why that table is built first.
fn type_ref(ty: &str, spec: &Spec) -> String {
    match spec.families.binary_search_by(|(name, _)| name.as_str().cmp(ty)) {
        Ok(index) => format!("TypeRef::Family(FamilyId({index}))"),
        Err(_) => format!("TypeRef::Concrete({})", string(ty)),
    }
}

/// A Rust string literal. Non-ASCII stays as-is — the generated files are
/// UTF-8 and the reference pages' `≥`, `×` and `✔` read better than escapes.
fn string(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
