export const ASKAMA_LANGUAGES = new Set([
  'askama-html',
  'askama-txt',
  'askama-rust',
  'askama-js',
  'askama-ts',
  'askama-toml',
  'askama-css',
  'askama-json',
  'askama-md',
  'askama-jsx',
  'askama-tsx',
  'askama-yaml',
  'askama-gitignore',
  'askama-env',
  'askama-swift',
]);
