[package]
name = "wgsl-analyzer"
version = "0.1.0"
edition = { workspace = true }
description = "WGSL shader validator and analyzer, compilable to WASM"
license = "MIT"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
naga = { version = "30.0.1", features = [ "wgsl-in", "glsl-in" ] }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
console_error_panic_hook = "0.1"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
