// Expands `languages.json` into the two places VS Code reads:
//
//   * `syntaxes/typst-embedded.tmLanguage.json` — one fenced-block rule per
//     language, each handing its contents to that language's grammar.
//   * `package.json` → `contributes.grammars[typst].embeddedLanguages` — the
//     scope→language map that makes the *editor* treat the block as that
//     language: its comment toggle, its brackets, its word pattern.
//
// Both are generated because they have to agree on every `meta.embedded.block.*`
// scope, and a table of sixty languages maintained in two files by hand would
// not stay in agreement. Run it after editing the table:
//
//     pnpm --filter wx-vsce-typst-ultra run build:grammar
//
// `--check` writes nothing and exits non-zero if either artifact is stale, which
// is what `src/embeddedLanguages.test.ts` runs — so a forgotten regeneration
// fails the suite rather than shipping.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const EXTENSION = join(HERE, '..', '..');

const TABLE = join(HERE, 'languages.json');
const GRAMMAR = join(EXTENSION, 'syntaxes', 'typst-embedded.tmLanguage.json');
const MANIFEST = join(EXTENSION, 'package.json');

/** The scope the generated grammar registers itself under. */
export const SCOPE = 'source.typst.embedded';

/**
 * @typedef {object} EmbeddedLanguage
 * @property {string} id VS Code language id: names the scope and the editor mode.
 * @property {string} scope TextMate scope whose grammar colours the contents.
 * @property {string[]} tags What the user writes after the backticks.
 * @property {'extension' | 'self'} [provider] Who ships the grammar, when it is
 *   not VS Code: a third-party extension, or this one.
 */

/** @returns {EmbeddedLanguage[]} The table, in the order it is written. */
export function readTable() {
  /** @type {{ languages: EmbeddedLanguage[] }} */
  const table = JSON.parse(readFileSync(TABLE, 'utf8'));
  return table.languages;
}

/** @param {string} tag @returns {string} The tag as a regex literal. */
function escape(tag) {
  return tag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * One raw-block rule.
 *
 * Three details carry the weight:
 *
 * * **`` (`{3,}) `` … `\1`.** Typst closes a raw block with the same run of
 *   backticks that opened it, so the end pattern is a back-reference rather
 *   than a literal — a four-backtick block may contain three.
 * * **`(?=[\s`]|$)` after the tag.** The tag has to *end* there. Without it the
 *   `c` rule would match ```` ```c++ ```` and leave `++` as code, because
 *   nothing in `[\w-]` follows the `c`.
 * * **`contentName`.** `meta.embedded.block.<id>` is both what themes colour
 *   and the key `embeddedLanguages` maps, so it is written once, here.
 *
 * @param {EmbeddedLanguage} language
 * @returns {object} A TextMate begin/end rule.
 */
function rule(language) {
  // Longest first: alternation is ordered, and `objc` must not win over
  // `objc++` on a prefix.
  const tags = [...language.tags].sort((a, b) => b.length - a.length || a.localeCompare(b));

  return {
    name: `markup.raw.block.${language.id}.typst`,
    contentName: `meta.embedded.block.${language.id}`,
    begin: `(\`{3,})((?i:${tags.map(escape).join('|')}))(?=[\\s\`]|$)`,
    end: '(\\1)',
    beginCaptures: {
      1: { name: 'punctuation.definition.raw.typst' },
      2: { name: 'fenced_code.block.language.typst' },
    },
    endCaptures: {
      1: { name: 'punctuation.definition.raw.typst' },
    },
    patterns: [{ include: language.scope }],
  };
}

/** @param {EmbeddedLanguage[]} languages @returns {object} The whole grammar. */
export function buildGrammar(languages) {
  return {
    $schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
    name: 'Typst Embedded Languages',
    scopeName: SCOPE,
    _comment:
      'Generated by scripts/embedded/generate.mjs from scripts/embedded/languages.json — do not edit. ' +
      'One rule per language a raw block can carry; `source.typst` includes the lot, ahead of its own ' +
      'untagged raw-block rule, so ```rust is coloured by rust and ```whatever is still coloured raw.',
    patterns: languages.map((language) => ({ include: `#${language.id}` })),
    repository: Object.fromEntries(languages.map((language) => [language.id, rule(language)])),
  };
}

/**
 * @param {EmbeddedLanguage[]} languages
 * @returns {Record<string, string>} `meta.embedded.block.rust` → `rust`.
 */
export function buildEmbeddedLanguages(languages) {
  return Object.fromEntries(
    languages.map((language) => [`meta.embedded.block.${language.id}`, language.id]),
  );
}

/**
 * @param {string} path
 * @param {string} contents
 * @param {boolean} check
 * @returns {boolean} Whether the file was, or would be, changed.
 */
function put(path, contents, check) {
  let current;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    current = undefined;
  }
  if (current === contents) return false;
  if (!check) writeFileSync(path, contents);
  return true;
}

/**
 * @param {{ check?: boolean, write?: (line: string) => void }} [options]
 * @returns {number} Process exit code.
 */
export function generate({ check = false, write = console.log } = {}) {
  const languages = readTable();
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));

  const typst = manifest.contributes.grammars.find(
    (/** @type {{ language?: string }} */ grammar) => grammar.language === 'typst',
  );
  if (!typst) throw new Error('package.json has no grammar contribution for `typst`');
  typst.embeddedLanguages = buildEmbeddedLanguages(languages);

  const stale = [
    put(GRAMMAR, JSON.stringify(buildGrammar(languages), null, 2) + '\n', check),
    put(MANIFEST, JSON.stringify(manifest, null, 2) + '\n', check),
  ].filter(Boolean).length;

  if (!check) {
    write(`${languages.length} embedded languages, ${countTags(languages)} tags`);
    return 0;
  }
  if (stale > 0) {
    write(`${stale} generated file(s) are stale. Run \`pnpm run build:grammar\`.`);
    return 1;
  }
  return 0;
}

/** @param {EmbeddedLanguage[]} languages @returns {number} */
function countTags(languages) {
  return languages.reduce((total, language) => total + language.tags.length, 0);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  process.exitCode = generate({ check: process.argv.includes('--check') });
}
